#version 450

#define EPSILON 0.00001

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform image2D resultImage;

layout (binding = 1) uniform UBO
{
	vec4 src;
} ubo;

bool is_hit_sphere(vec3 src, vec3 dst, float far, vec3 sphere, float radius)
{
	vec3 p = src;
	vec3 r = dst;
	vec3 pc = p - sphere;
	float a = dot(r, r);
	float b = dot(r, pc) * 2;
	float c = dot(pc, pc) - radius * radius;

	float delta = b * b - 4 * a * c;

	if (delta > EPSILON) {
		// return true;
		float sqrt_delta = sqrt(delta);
		float t1 = (-b + sqrt_delta) / (2 * a);
		float t2 = (-b - sqrt_delta) / (2 * a);

		bool hit_anything = false;
		if (t1 > EPSILON && t1 < far) {
			// t = t1;
			far = t1;
			hit_anything = true;
		} 
		if (t2 > EPSILON && t2 < far) {
			// t = t2;
			hit_anything = true;
		}

		return hit_anything;
	}

	return false;
}

void main()
{
	ivec2 extent2d = imageSize(resultImage);
	vec3 dst = vec3(vec2(gl_GlobalInvocationID.xy) / extent2d * 2.0 - 1.0, -1.0);
	// vec3 src = ubo.src.xyz;
	vec3 src = vec3(0.0);

	vec3 outcolor = vec3(0.0);
	if (is_hit_sphere(src, dst, 10.0, vec3(0.0, 0.0, -1.0), 0.3)) {
		outcolor = vec3(0.4, 0.4, 0.4);
	} else {
		outcolor = vec3(0.1, 0.2, 0.4);
	}

	imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(outcolor, 0.0));
}