#pragma once

#include "cvk/vk_header.h"
#include "cvk/base/base_memorized.h"
#include "cvk/image/base_image_view.h"
#include "cvk/image/image2d.h"

namespace cvk
{
    
    // typedef BaseMemorized<Image2D> MemorizedImage2D;
    typedef BaseTypeImageView<VK_IMAGE_VIEW_TYPE_2D, VK_IMAGE_ASPECT_COLOR_BIT> ColorImageView2D;
    // typedef MemorizedImageView<ImageView2D> MemorizedImageView2D;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> StandardTexture2D;
    typedef BaseTypeTexture2D<MEMORY_WRITABLE, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> WritableTexture2D;
    typedef BaseTypeTexture2D<MEMORY_WRITABLE_FULL_SPEED, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> WritableTexture2DFullSpeed;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> StandardColorAttachment2D;
    typedef BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> ReadableColorAttachment2D;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> StandardInputAttachment2D;
    typedef BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> ReadableInputAttachment2D;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_DEPTH_BIT> StandardDepthAttachment2D;
    
} // namespace cvk
