#pragma once

#include "cvk/vk_header.h"
#include "cvk/base/base_memorized.h"
#include "cvk/image/base_image_view.h"
#include "cvk/image/texture2d.h"

namespace cvk
{
    
    // typedef BaseMemorized<Image2D> MemorizedImage2D;
    typedef BaseTypeImageView<VK_IMAGE_VIEW_TYPE_2D, VK_IMAGE_ASPECT_COLOR_BIT> ColorImageView2D;
    // typedef MemorizedImageView<ImageView2D> MemorizedImageView2D;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> Texture2D;
    typedef BaseTypeTexture2D<MEMORY_WRITABLE, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> Texture2DWritable;
    typedef BaseTypeTexture2D<MEMORY_WRITABLE_SPEED, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> Texture2DWritableSpeed;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> ColorAttachment2D;
    typedef BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> ColorAttachment2DReadable;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> ColorAttachTexture2D;
    typedef BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> ColorAttachTexture2DReadable;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> ColorAttachInput2D;
    typedef BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT> ColorAttachInput2DReadable;

    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_DEPTH_BIT> DepthAttachment2D;
    
} // namespace cvk

namespace cvk
{
    
    typedef BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_STORAGE_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT> StorageImage2D;

} // namespace cvk

