#pragma once

#include "cvk/vk_header.h"
#include "cvk/base/base_memorized.h"
#include "cvk/image/base_image_view.h"
#include "cvk/image/texture2d.h"
#include "cvk/image/sampler.h"

namespace cvk
{
    
    // using MemorizedImage2D = BaseMemorized<Image2D>;
    using ColorImageView2D = BaseTypeImageView<VK_IMAGE_VIEW_TYPE_2D, VK_IMAGE_ASPECT_COLOR_BIT>;
    // using MemorizedImageView2D = MemorizedImageView<ImageView2D>;

    using Texture2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT>;
    using Texture2DWritable = BaseTypeTexture2D<MEMORY_WRITABLE, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT>;
    using Texture2DWritableSpeed = BaseTypeTexture2D<MEMORY_WRITABLE_SPEED, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT>;

    using ColorAttachment2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT>;
    using ColorAttachment2DReadable = BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT>;

    using ColorAttachTexture2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT>;
    using ColorAttachTexture2DReadable = BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT>;

    using ColorAttachInput2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT>;
    using ColorAttachInput2DReadable = BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT>;

    using DepthAttachment2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_DEPTH_BIT>;
    
    using StorageImage2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_STORAGE_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT>;
    using StorageImage2DReadable = BaseTypeTexture2D<MEMORY_READABLE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_STORAGE_BIT, VK_IMAGE_TILING_LINEAR, VK_IMAGE_ASPECT_COLOR_BIT>;
    using StorageTexture2D = BaseTypeTexture2D<MEMORY_STANDARD, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_STORAGE_BIT, VK_IMAGE_TILING_OPTIMAL, VK_IMAGE_ASPECT_COLOR_BIT>;

} // namespace cvk

